name: offbench-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.8
  - cudnn=8.2
  - git
  - mesa-libgl-cos6-x86_64
  - glew
  - wget
  - tmux
  - htop
  - rsync
  - patchelf
  - pip:
      - numpy==1.26.4
      - scipy==1.12.0
      # - protobuf==3.20.3
      - PyYAML
      - wandb
      - rlds
      - tensorflow==2.15.1
      - tensorflow-datasets==4.9.0
      - dm-acme==0.4.0
      - dm-sonnet==2.0.1
      - dm-reverb[tensorflow]
      - "jax[cuda11_cudnn82]==0.4.13"
      - jaxlib==0.4.13
      - optax==0.1.5
      - chex==0.1.7
      - distrax==0.1.3
      - free-mujoco-py==2.1.6
      - ml_collections
      - flax==0.6.10
      - orbax==0.1.7
      - git+https://github.com/Farama-Foundation/d4rl@master#egg=d4rl
